options:
  log_bucket: gs://resume-logs-bucket

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/t-science-434802-f8/visitor-counter-service', '.']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/t-science-434802-f8/visitor-counter-service']
    
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'visitor-counter-service',
      '--image', 'gcr.io/t-science-434802-f8/visitor-counter-service',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
