name: CI/CD to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Authenticate Docker to Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cloud-run-repo/function-1 .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cloud-run-repo/function-1

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy function-1 \
        --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cloud-run-repo/function-1 \
        --platform managed \
        --region ${{ secrets.REGION }} \
        --allow-unauthenticated
